# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartnerPlus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PartnerPlus
  pod 'Mixpanel'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  target 'PartnerPlusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PartnerPlus-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PartnerPlus-tvOS

  target 'PartnerPlus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
