export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';

export const NAME = 'name';
export const AUTH_TOKEN = 'auth_token';
export const AUTH_STORE = 'BizongoUserAuthStore';

export const GET_STATE = 'GET_STATE';
export const GET_STATE_REQUEST = 'GET_STATE_REQUEST';
export const GET_STATE_COMPLETE = 'GET_STATE_COMPLETE';
export const GET_STATE_ERROR = 'GET_STATE_ERROR';

export const FETCH_RATING_REQUEST = 'FETCH_RATING_REQUEST';
export const FETCH_RATING_COMPLETE = 'FETCH_RATING_COMPLETE';
export const FETCH_RATING_ERROR = 'FETCH_RATING_ERROR';

export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_COMPLETE = 'FETCH_NOTIFICATION_COMPLETE';
export const FETCH_NOTIFICATION_ERROR = 'FETCH_NOTIFICATION_ERROR';

export const FETCH_SETTLEMENTS_REQUEST = 'FETCH_SETTLEMENTS_REQUEST';
export const FETCH_SETTLEMENTS_COMPLETE = 'FETCH_SETTLEMENTS_COMPLETE';
export const FETCH_SETTLEMENTS_ERROR = 'FETCH_SETTLEMENTS_ERROR';

export const DOWNLOAD_SETTLEMENTS_REQUEST = 'DOWNLOAD_SETTLEMENTS_REQUEST';
export const DOWNLOAD_SETTLEMENTS_COMPLETE = 'DOWNLOAD_SETTLEMENTS_COMPLETE';
export const DOWNLOAD_SETTLEMENTS_ERROR = 'DOWNLOAD_SETTLEMENTS_ERROR';

export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST';
export const FETCH_ALL_PRODUCTS_COMPLETE = 'FETCH_ALL_PRODUCTS_COMPLETE';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_COMPLETE = 'FETCH_PRODUCT_COMPLETE';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

// export const FETCH_SKU_REQUEST = 'FETCH_SKU_REQUEST';
// export const FETCH_SKU_COMPLETE = 'FETCH_SKU_COMPLETE';
// export const FETCH_SKU_ERROR = 'FETCH_SKU_ERROR';

export const EMAIL_VALIDATE_REQUEST = 'EMAIL_VALIDATE_REQUEST';
export const EMAIL_VALIDATE_COMPLETE = 'EMAIL_VALIDATE_COMPLETE';
export const EMAIL_VALIDATE_ERROR = 'EMAIL_VALIDATE_ERROR';

export const PHONE_VALIDATE_REQUEST = 'PHONE_VALIDATE_REQUEST';
export const PHONE_VALIDATE_COMPLETE = 'PHONE_VALIDATE_COMPLETE';
export const PHONE_VALIDATE_ERROR = 'PHONE_VALIDATE_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_COMPLETE = 'SIGNUP_COMPLETE';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_COMPLETE = 'SEND_OTP_COMPLETE';
export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_COMPLETE = 'VERIFY_OTP_COMPLETE';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';

export const LOAD_CATEGORIES_REQUEST = 'LOAD_CATEGORIES_REQUEST';
export const LOAD_CATEGORIES_COMPLETE = 'LOAD_CATEGORIES_COMPLETE';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';

export const REGISTER_COMPANY_REQUEST = 'REGISTER_COMPANY_REQUEST';
export const REGISTER_COMPANY_COMPLETE = 'REGISTER_COMPANY_COMPLETE';
export const REGISTER_COMPANY_ERROR = 'REGISTER_COMPANY_ERROR';

export const REGISTER_BILLING_DETAILS_REQUEST =
  'REGISTER_BILLING_DETAILS_REQUEST';
export const REGISTER_BILLING_DETAILS_COMPLETE =
  'REGISTER_BILLING_DETAILS_COMPLETE';
export const REGISTER_BILLING_DETAILS_ERROR = 'REGISTER_BILLING_DETAILS_ERROR';

export const RESET_SIGNUP_STATE = 'RESET_SIGNUP_STATE';
export const PRODUCT_RESET = 'PRODUCT_RESET';

export const USER_CONFIRMATION_REQUEST = 'USER_CONFIRMATION_REQUEST';
export const USER_CONFIRMATION_COMPLETE = 'USER_CONFIRMATION_COMPLETE';
export const USER_CONFIRMATION_ERROR = 'USER_CONFIRMATION_ERROR';

export const FETCH_COMPANY_REQUEST = 'FETCH_COMPANY_REQUEST';
export const FETCH_COMPANY_COMPLETE = 'FETCH_COMPANY_COMPLETE';
export const FETCH_COMPANY_ERROR = 'FETCH_COMPANY_ERROR';

export const SAVE_COMPANY_REQUEST = 'SAVE_COMPANY_REQUEST';
export const SAVE_COMPANY_COMPLETE = 'SAVE_COMPANY_COMPLETE';
export const SAVE_COMPANY_ERROR = 'SAVE_COMPANY_ERROR';

export const SAVE_COMPANY_STATUTORY_REQUEST = 'SAVE_COMPANY_STATUTORY_REQUEST';
export const SAVE_COMPANY_STATUTORY_COMPLETE =
  'SAVE_COMPANY_STATUTORY_COMPLETE';
export const SAVE_COMPANY_STATUTORY_ERROR = 'SAVE_COMPANY_STATUTORY_ERROR';

// export const FETCH_ORDER_DETAILS_REQUEST = 'FETCH_ORDER_DETAILS_REQUEST';
// export const FETCH_ORDER_DETAILS_COMPLETE = 'FETCH_ORDER_DETAILS_COMPLETE';
// export const FETCH_ORDER_DETAILS_ERROR = 'FETCH_ORDER_DETAILS_ERROR';
// export const RESET_ORDER_DETAILS = 'RESET_ORDER_DETAILS';

// export const ACCEPT_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
// export const ACCEPT_ORDER_COMPLETE = 'ACCEPT_ORDER_COMPLETE';
// export const ACCEPT_ORDER_ERROR = 'ACCEPT_ORDER_ERROR';

// export const REJECT_ORDER_REQUEST = 'REJECT_ORDER_REQUEST';
// export const REJECT_ORDER_COMPLETE = 'REJECT_ORDER_COMPLETE';
// export const REJECT_ORDER_ERROR = 'REJECT_ORDER_ERROR';

// export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
// export const FETCH_ORDERS_COMPLETE = 'FETCH_ORDERS_COMPLETE';
// export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';

export const FETCH_ADDRESSES_REQUEST = 'FETCH_ADDRESSES_REQUEST';
export const FETCH_ADDRESSES_COMPLETE = 'FETCH_ADDRESSES_COMPLETE';
export const FETCH_ADDRESSES_ERROR = 'FETCH_ADDRESSES_ERROR';

// export const CREATE_SHIPMENT_REQUEST = 'CREATE_SHIPMENT_REQUEST';
// export const CREATE_SHIPMENT_COMPLETE = 'CREATE_SHIPMENT_COMPLETE';
// export const CREATE_SHIPMENT_ERROR = 'CREATE_SHIPMENT_ERROR';

// export const FETCH_SETTLEMENT_DETAILS_REQUEST =
//   'FETCH_SETTLEMENT_DETAILS_REQUEST';
// export const FETCH_SETTLEMENT_DETAILS_COMPLETE =
//   'FETCH_SETTLEMENT_DETAILS_COMPLETE';
// export const FETCH_SETTLEMENT_DETAILS_ERROR = 'FETCH_SETTLEMENT_DETAILS_ERROR';
// export const RESET_SETTLEMENT_DETAILS_DATA = 'RESET_SETTLEMENT_DETAILS_DATA';

// export const FETCH_STOCKS_REQUEST = 'FETCH_STOCKS_REQUEST';
// export const FETCH_STOCKS_COMPLETE = 'FETCH_STOCKS_COMPLETE';
// export const FETCH_STOCKS_ERROR = 'FETCH_STOCKS_ERROR';

/* actions to fetch Request for Quotes */
export const FETCH_INQUIRIES_REQUEST = 'FETCH_INQUIRIES_REQUEST';
export const FETCH_INQUIRIES_COMPLETE = 'FETCH_INQUIRIES_COMPLETE';
export const FETCH_INQUIRIES_ERROR = 'FETCH_INQUIRIES_ERROR';

export const FETCH_INQUIRY_REQUEST = 'FETCH_INQUIRY_REQUEST';
export const FETCH_INQUIRY_COMPLETE = 'FETCH_INQUIRY_COMPLETE';
export const FETCH_INQUIRY_ERROR = 'FETCH_INQUIRY_ERROR';

export const FETCH_INQUIRY_HISTORY_REQUEST = 'FETCH_INQUIRY_HISTORY_REQUEST';
export const FETCH_INQUIRY_HISTORY_COMPLETE = 'FETCH_INQUIRY_HISTORY_COMPLETE';
export const FETCH_INQUIRY_HISTORY_ERROR = 'FETCH_INQUIRY_HISTORY_ERROR';

/*actions for prev shipment fetch*/
// export const FETCH_PREV_SHIPMENT_REQUEST = 'FETCH_PREV_SHIPMENT_REQUEST';
// export const FETCH_PREV_SHIPMENT_COMPLETE = 'FETCH_PREV_SHIPMENT_COMPLETE';
// export const FETCH_PREV_SHIPMENT_ERROR = 'FETCH_PREV_SHIPMENT_ERROR';

// export const FETCH_SHIPMENTS_REQUEST = 'FETCH_SHIPMENTS_REQUEST';
// export const FETCH_SHIPMENTS_COMPLETE = 'FETCH_SHIPMENTS_COMPLETE';
// export const FETCH_SHIPMENTS_ERROR = 'FETCH_SHIPMENTS_ERROR';

/* actions to fetch Purchase Orders */
export const FETCH_PURCHASE_ORDERS_REQUEST = 'FETCH_PURCHASE_ORDERS_REQUEST';
export const FETCH_PURCHASE_ORDERS_COMPLETE = 'FETCH_PURCHASE_ORDERS_COMPLETE';
export const FETCH_PURCHASE_ORDERS_ERROR = 'FETCH_PURCHASE_ORDERS_ERROR';

export const FETCH_PURCHASE_ORDER_REQUEST = 'FETCH_PURCHASE_ORDER_REQUEST';
export const FETCH_PURCHASE_ORDER_COMPLETE = 'FETCH_PURCHASE_ORDER_COMPLETE';
export const FETCH_PURCHASE_ORDER_ERROR = 'FETCH_PURCHASE_ORDER_ERROR';

export const FETCH_PURCHASE_ORDER_ITEMS_REQUEST =
  'FETCH_PURCHASE_ORDER_ITEMS_REQUEST';
export const FETCH_PURCHASE_ORDER_ITEMS_COMPLETE =
  'FETCH_PURCHASE_ORDER_ITEMS_COMPLETE';
export const FETCH_PURCHASE_ORDER_ITEMS_ERROR =
  'FETCH_PURCHASE_ORDER_ITEMS_ERROR';

export const FETCH_PURCHASE_ORDER_DISPATCH_PLANS_REQUEST =
  'FETCH_PURCHASE_ORDER_DISPATCH_PLANS_REQUEST';
export const FETCH_PURCHASE_ORDER_DISPATCH_PLANS_COMPLETE =
  'FETCH_PURCHASE_ORDER_DISPATCH_PLANS_COMPLETE';
export const FETCH_PURCHASE_ORDER_DISPATCH_PLANS_ERROR =
  'FETCH_PURCHASE_ORDER_DISPATCH_PLANS_ERROR';
